version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto8
  pre_build:
    commands:
      - echo Entered Pre Build Stage
      - set -e -u -x
      - mkdir artifacts
      - cd artifacts
      - mkdir integration
      - mkdir prelive
      - mkdir development
      - cd ../cdk
      - npm install
      - npm install -g typescript
  build:
    commands:
      - echo Entered Build Stage
      - echo Build Started
      - npm run build
      - echo Executing Synth for Integration
      - npx cdk bootstrap aws://064524996963/eu-west-1 aws://221090739390/eu-west-1
      - npx cdk synth
      - ls
      - cp -R ./cdk.out ../artifacts/integration
      - cp ../buildspec.yml ../artifacts
      - cp ../deployspec.yml ../artifacts
      - cp ../deployintspec.yml ../artifacts
      - cp ../deployprodspec.yml ../artifacts
artifacts:
  files:
    - ./artifacts/**/*
