version: 0.2

phases:
  build:
    commands:
      - echo Entered Build Stage
      - echo Build Started
      - mkdir artifacts
      - cp ./buildspec.yml artifacts
      - cp ./depec.yml artifacts
artifacts:
  files:
    - ./artifacts/*
