version: 0.2

phases:
  build:
    commands:
      - echo Entered Build Stage
      - echo Build Started
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - ./buildspec.yml
    artifact2:
      files:
        - ./deployspec.yml
