version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: corretto8
  pre_build:
    commands:
      - echo Test Build
      - mkdir artifacts
  build:
    commands:
      - echo Test Building
      - cp ./buildspec.yml ./artifacts/
      - cp ./deployspec.yml ./artifacts/
      - cp ./deployintspec.yml ./artifacts/
      - cp ./deployprodspec.yml ./artifacts/
      - cp ./versiontest.txt ./artifacts/
artifacts:
  files:
    - '**/*'
  base-directory: artifacts
