version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: corretto8
  pre_build:
    commands:
      - echo Test Build
  build:
    commands:
      -echo Test Building
artifacts:
  files:
    - ./versiontest.txt
