version: 0.2

phases:
  build:
    commands:
      - echo Entered Build Stage
      - echo Build Started
artifacts:
  files:
    - ./buildspec.yml
  secondary-artifacts:
    artifact1:
      files:
        - ./deployspec.yml
