version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: corretto8
  pre_build:
    commands:
      - echo Entered Pre Build Stage
      - set -e -u -x
      - mkdir artifacts
      - cd artifacts
      - mkdir development
      - cd ../cdk
      - npm install
      - npm install -g aws-cdk
      - npm install cdk-assume-role-credential-plugin
  build:
    commands:
      - echo Entered Build Stage
      - echo Build Started
      - npm run build
      - echo Executing Synth for Integration
      - npx cdk synth --plugin cdk-assume-role-credential-plugin --context assume-role-credentials:writeIamRoleName=cdk-writeRole --context assume-role-credentials:readIamRoleName=cdk-readOnlyRole
      - cp ./cdk.out ../artifacts/development
      - cp ../buildspec.yml ../artifacts
      - cp ../deployspec.yml ../artifacts
      - cp ../deployintspec.yml ../artifacts
      - cp ../deployprodspec.yml ../artifacts
artifacts:
  files:
    - ./artifacts/**/*
