version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: corretto8
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_artifactbucket
      - ls
      - cat trial.txt
artifacts:
  files:
    - '**/*'
  base-directory: artifacts
